[package]
name = "manufacture"
version = "0.1.0"
authors = ["Maxis Maximov Jr."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.1"
crossterm = "0.27.0"
rand = "0.8.5"
serde_json = "1.0.114"
